import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#fff" },
  loadingContainer: { flex: 1, justifyContent: "center", alignItems: "center" },
  imageWrapper: { width: "100%", height: 320, position: "relative" },
  mainImage: { width: "100%", height: "100%", backgroundColor: "#F5F5F5" },
  topBar: {
    position: "absolute",
    left: 16,
    right: 16,
    flexDirection: "row",
    justifyContent: "space-between",
  },
  topBarRight: { flexDirection: "row", gap: 12 },
  iconCircle: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "#fff",
    justifyContent: "center",
    alignItems: "center",
    elevation: 2,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  content: { padding: 20, paddingTop: 16 },
  headerRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: 12,
  },
  title: {
    flex: 1,
    fontSize: 24,
    fontWeight: "bold",
    color: "#171717",
    marginRight: 16,
  },
  priceContainer: { alignItems: "flex-end" },
  priceValue: { fontSize: 28, fontWeight: "bold", color: "#F97316" },
  priceCurrency: { fontSize: 16 },
  priceSuffix: { fontSize: 12, color: "#A3A3A3", marginTop: -4 },
  locationRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginBottom: 16,
  },
  locationText: { fontSize: 14, color: "#737373" },
  tagsRow: { flexDirection: "row", flexWrap: "wrap", gap: 8, marginBottom: 24 },
  tagPill: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 12,
    gap: 6,
  },
  tagText: { fontSize: 12, fontWeight: "600" },
  sectionTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#171717",
    marginBottom: 12,
  },
  description: {
    fontSize: 15,
    color: "#4B5563",
    lineHeight: 24,
    marginBottom: 8,
  },
  divider: { height: 1, backgroundColor: "#F3F4F6", marginVertical: 24 },
  receiptCard: {
    backgroundColor: "#FFF7ED",
    borderColor: "#FDBA74",
    borderWidth: 1,
    borderRadius: 16,
    padding: 20,
    marginBottom: 24,
  },
  receiptRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
  },
  receiptBorder: {
    borderBottomWidth: 1,
    borderBottomColor: "#FDBA74",
    paddingBottom: 16,
    marginBottom: 16,
  },
  receiptText: { fontSize: 15, color: "#4B5563" },
  receiptValue: { fontSize: 15, color: "#171717", fontWeight: "600" },
  receiptTotalText: { fontSize: 18, fontWeight: "bold", color: "#171717" },
  receiptTotalValue: { fontSize: 20, fontWeight: "bold", color: "#F97316" },
  infoBox: {
    flexDirection: "row",
    backgroundColor: "#F0F9FF",
    padding: 16,
    borderRadius: 16,
    gap: 12,
  },
  infoText: { flex: 1, fontSize: 13, color: "#0369A1", lineHeight: 20 },
  bottomBar: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: "#fff",
    paddingTop: 16,
    paddingHorizontal: 20,
    borderTopWidth: 1,
    borderTopColor: "#F3F4F6",
  },
  actionButton: {
    flexDirection: "row",
    paddingVertical: 16,
    paddingHorizontal: 24,
    borderRadius: 24,
    alignItems: "center",
    justifyContent: "center",
  },
  actionButtonText: { color: "#fff", fontSize: 16, fontWeight: "bold" },
  buttonPriceBadge: {
    backgroundColor: "rgba(255,255,255,0.2)",
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 12,
    marginLeft: 12,
  },
  buttonPriceText: { color: "#fff", fontWeight: "bold", fontSize: 14 },
});
